<?php
use Core\Models\Config;
use Core\Models\Session\Session;
use Core\Views\View;


if (Config::get('session_on') && Config::get('csrf_on')) : ?>
    <?= Session::CSRFRenderHiddenField(); ?>
<?php endif; ?>
<script type="text/javascript">
    var rootUrl = "<?= Config::get("url") ?>";
    var developmentMode = "<?= Config::get('developmentMode') ?>";
</script>
<?php View::renderDefaultJSFiles(); ?>
<?php View::renderCustomJSFiles(); ?>
</body>

</html>