<?php
use Boostack\Models\Config;
use Boostack\Models\Language;
use Boostack\Models\Request;
use Boostack\Models\Auth;

?>
<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2 class="text-white textShadow display-4"><?= Language::getLabel("navigation.login");?></h2>
            </div>
        </div>
    </div>
</section>
<p>&nbsp;</p>
<section class="login centerContent py-5 fw-light">
    <div class="container">
        <div class="row">
            <div id="" class="col-md-1">
            </div> 
            <div id="loginbox" class="col-md-4 ">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title"><?= Language::getLabel("form.login.signin");?></h3>
                    </div>
                    <div class="card-body">
                        <div class="text-end">
                                <small> <a href="<?= Request::getFriendlyUrl("login");?>">
                                        <?= Language::getLabel("form.login.forgotpwd");?>
                                    </a>
                                </small>
                            </div>
                        <?php if(!Auth::isTimerLocked()): ?>
                            <div id="login-alert" class="alert alert-danger col-sm-12 <?= $errorMessage == "" ? "d-none" : "" ?>"><?= $errorMessage; ?></div>
                            <form id="loginform"
                                action="<?= Request::getFriendlyUrl("login");?>" name="loginform"
                                class="form-horizontal" method="post" role="form">

                                <div style="margin-bottom: 25px; margin-top: 25px;"
                                    class="input-group">
                                    <div class="input-group-addon">
                                        <i class="glyphicon glyphicon-user"></i>
                                    </div>
                                    <input id="btk_usr" type="text" class="form-control"
                                        name="btk_usr" placeholder="E-mail" value="" />
                                </div>

                                <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-lock"></i></span> <input
                                        id="btk_pwd" type="password" class="form-control"
                                        name="btk_pwd" placeholder="Password" value="" />
                                </div>

                                <?php if(Auth::haveToShowCaptcha()): ?>
                                    <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
                                    <script>
                                        var captchaResult = false;
                                        function verifyCaptcha(response){
                                            if(response) captchaResult = true;
                                        }
                                    </script>
                                    <div id="reCaptcha-align">
                                        <div name="response" class="g-recaptcha" data-callback="verifyCaptcha"
                                            data-sitekey="<?= Config::get("reCaptcha_public") ?>"></div>
                                    </div>
                                    <br>
                                <?php endif; ?>

                                <p id="form-validation-error" class="text-danger"></p>

                                <div class="input-group">
                                    <div class="checkbox">
                                        <label> <input id="login-remember" type="checkbox" name="rememberme" value="1" /><?= Language::getLabel("form.login.rememberme");?>
                                        </label>
                                    </div>
                                </div>

                                <div style="margin-top: 10px" class="form-group">
                                    <div class="col-sm-12 controls">
                                        <input type="button" id="btn-login" class="btn btn-dark " value="<?= Language::getLabel("login.login");?>" />

                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div>
                                            <hr/>
                                            <small>
                                                <a href="<?= Request::getFriendlyUrl("registration");?>"><?= Language::getLabel("login.donthaveaccount");?></a>
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        <?php else: ?>
                            <div id="login-alert" class="alert alert-danger col-sm-12">Too much login request. Wait some seconds</div>
                        <?php endif; ?>
                        <div class="form-group">
                            <div class="col-md-12 control">
                                <div style=" padding-top: 10px;">
                                    <small>
                                        [User Privilege]<br/>
                                        User or Email: <b>boostackuser</b> or <b>user@getboostack.com</b> - Password: <b>testing</b></a><hr/>
                                        [Admin Privilege]<br/>
                                        User or Email: <b>boostackadmin</b> or <b>admin@getboostack.com</b> - Password: <b>testing</b></a><hr/>
                                        [SuperAdmin Privilege]<br/>
                                        User or Email: <b>boostacksuperadmin</b> or <b>superadmin@getboostack.com</b> - Password: <b>testing</b></a><hr/>


                                        <div class="passwordBox">
                                            <div class="card panel-default">
                                                <div class="card-body" style="overflow: scroll;">
                                                    <p>Insert this password in table "boostack_user" in field "pwd":</p>
                                                    <i><?php
                                                        echo (version_compare(PHP_VERSION, '5.6.0') >= 0)?password_hash('testing',PASSWORD_DEFAULT):hash("sha512", 'testing');
                                                        ?>
                                                    </i>
                                                </div>
                                            </div>

                                        </div>
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="" class="col-md-2">
            </div> 
            <div id="" class="col-md-4">                

            <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title"><?= Language::getLabel("form.login.signin-ajax");?></h3>
                    </div>
                    <div class="card-body">
                    <?php try{
                        if(Config::constraint("api_on")){?>
                            <div id="login-alert" class="alert alert-danger col-sm-12 <?= $errorMessage == "" ? "d-none" : "" ?>"><?= $errorMessage; ?></div>
                            <form id="loginform-ajax"
                                action="<?= Request::getFriendlyUrl("login");?>" name="loginform-ajax"
                                class="form-horizontal" method="post" role="form">

                                <div class="input-group mb-3 mt-3">
                                    <div class="input-group-addon">
                                        <i class="glyphicon glyphicon-user"></i>
                                    </div>
                                    <input id="btk_usr-ajax" type="text" class="form-control"
                                        name="btk_usr-ajax" placeholder="E-mail" value="" />
                                </div>

                                <div class="input-grou mb-3">
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-lock"></i></span> <input
                                        id="btk_pwd-ajax" type="password" class="form-control"
                                        name="btk_pwd-ajax" placeholder="Password" value="" />
                                </div>

                                <p id="form-validation-error-ajax" class="text-danger"></p>

                                <div class="input-group">
                                    <div class="checkbox">
                                        <label> <input id="login-remember-ajax" type="checkbox" name="rememberme-ajax" value="1" /><?= Language::getLabel("form.login.rememberme");?>
                                        </label>
                                    </div>
                                </div>

                                <div style="margin-top: 10px" class="form-group">
                                    <div class="col-sm-12 controls">
                                        <input type="button" id="btn-login-ajax" class="btn btn-dark " value="<?= Language::getLabel("login.login");?>" />

                                    </div>
                                </div>
                            </form>          
                            <?php }
                    }
                    catch (\Boostack\Exception\Exception_Misconfiguration $e){
                        echo $e->getMessage();
                    }?>             
                    </div>
                </div>
            </div>

            <div id="" class="col-md-1">
            </div> 
        </div>                    
    </div>
</section>