<section class="disclaimer sectionTitle">
	<div class="line">
		<div class="container">
			<div class="row">
				<h1><?=$boostack->getLabel("error.attention")?></h1>
			</div>
		</div>
	</div>
</section>

<section class="download centerContent">
	<div class="container">
		<div class="row description">
			<h2><?=$boostack->getLabel("error.urlnotfound")?></h2>
			<p>
				<a href="<?=$boostack->url?>"><?=$boostack->url?></a>
			</p>
		</div>
	</div>
</section>