<section class="disclaimer sectionTitle">
	<div class="line">
		<div class="container">
			<div class="row">
				<h1><?=$boostack->getLabel("navigation.login");?></h1>
			</div>
		</div>
	</div>
</section>
<p>&nbsp;</p>
<section class="login centerContent">
	<div class="container">
		<div id="loginbox"
			class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
			<div class="panel panel-success">
				<div class="panel-heading">
					<div class="pull-right">
						<small> <a href="<?=$boostack->getFriendlyUrl("login");?>">
    								<?=$boostack->getLabel("login.forgotpwd");?>
    							</a>
						</small>
					</div>
					<div class="panel-title"><?=$boostack->getLabel("login.signin");?></div>
				</div>

				<div class="panel-body">

					<div id="login-alert" class="alert alert-danger col-sm-12 <?=($error=="")?"hidden":"";?>"><?=$error;?></div>

					<form id="loginform"
						action="<?=$boostack->getFriendlyUrl("login");?>" name="loginform"
						class="form-horizontal" method="post" role="form">

						<div class="form-group">
							<div class="col-md-12 control">
								<div style=" padding-top: 10px;">
									<small>Email: <b>testing@testing.com</b> - Password: <b>testing</b></a>
									</small>
								</div>
							</div>
						</div>
						
						<div style="margin-bottom: 25px; margin-top: 25px;"
							class="input-group">
							<div class="input-group-addon">
								<i class="glyphicon glyphicon-user"></i>
							</div>
							<input id="btk_usr" type="text" class="form-control"
								name="btk_usr" placeholder="E-mail" value="" />
						</div>

						<div style="margin-bottom: 25px" class="input-group">
							<span class="input-group-addon"><i
								class="glyphicon glyphicon-lock"></i></span> <input
								id="btk_pwd" type="password" class="form-control"
								name="btk_pwd" placeholder="Password" value="" />
						</div>

						<div class="input-group">
							<div class="checkbox">
								<label> <input id="login-remember" type="checkbox" name="rememberme" value="1" /><?=$boostack->getLabel("login.rememberme");?>
								</label>
							</div>
						</div>

						<div style="margin-top: 10px" class="form-group">
							<div class="col-sm-12 controls">
								<a id="btn-login" href="#" class="btn btn-default"
									onclick="CSRFCheckManager.addToForm(loginform);loginform.submit();return false;"><?=$boostack->getLabel("login.login");?></a>

							</div>
						</div>

						<div class="form-group">
							<div class="col-md-12 control">
								<div style="border-top: 1px solid #888; padding-top: 15px;">
									<small>
										<a href="<?=$boostack->getFriendlyUrl("registration");?>"><?=$boostack->getLabel("login.donthaveaccount");?></a>
									</small>
								</div>
							</div>
						</div>

                      </form>
				</div>
			</div>
		</div>
	</div>
</section>