<section class="disclaimer">
    <div class="line">
        <div class="container">
            <div class="row">
                <h1>
                    <span class="fadeInLeft animated"><span class="title"><?=$boostack->getLabel("projectName");?></span> <?=$boostack->getLabel("mainDescription");?></span><br/>
                    <span class="animated fadeInDown smaller"><?=$boostack->getLabel("mission");?></span>
                </h1>
            </div>
            <div class="row text-center animated fadeInUp">
                <a href="<?=$boostack->getFriendlyUrl("download")?>" class="btn btn-lg download"><?=$boostack->getLabel("downloadBoostack");?></a>
            </div>
        </div>
    </div>
</section>

<section class="features">
    <div class="container animated fadeIn">
        <div class="row">
            <div class="col-md-4">
                <h2><span><?=$boostack->getLabel("featuresTitles.fast");?></span></h2>
                <p>
                    <?=$boostack->getLabel("featuresDescriptions.fast");?>
                </p>
            </div>
            <div class="col-md-4">
                <h2><span><?=$boostack->getLabel("featuresTitles.freedom");?></span></h2>
                <p>
                    <?=$boostack->getLabel("featuresDescriptions.freedom");?>
                </p>
            </div>
            <div class="col-md-4">
                <h2><span><?=$boostack->getLabel("featuresTitles.simplicity");?></span></h2>
                <p>
                    <?=$boostack->getLabel("featuresDescriptions.simplicity");?>
                </p>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-4">
                <h2><span><?=$boostack->getLabel("featuresTitles.seo");?></span></h2>
                <p>
                    <?=$boostack->getLabel("featuresDescriptions.seo");?>
                </p>
            </div>
            <div class="col-md-4">
                <h2><span><?=$boostack->getLabel("featuresTitles.extensible");?></span></h2>
                <p>
                    <?=$boostack->getLabel("featuresDescriptions.extensible");?>
                </p>
            </div>
            <div class="col-md-4">
                <h2><span><?=$boostack->getLabel("featuresTitles.secure");?></span></h2>
                <p>
                    <?=$boostack->getLabel("featuresDescriptions.secure");?>
                </p>
            </div>
        </div>

        <div class="row text-center">
            <p>&nbsp;</p><p>&nbsp;</p>
            <h4><?=$boostack->getLabel("inclusions")?></h4>
            <a href="<?=$boostack->getFriendlyUrl("download")?>" class="btn btn-lg download"><?=$boostack->getLabel("downloadBoostack");?></a>
        </div>
    </div>
</section>