<section class="disclaimer sectionTitle">
	<div class="line">
		<div class="container">
			<div class="row">
				<h2><?=$boostack->getLabel("navigation.documentation");?></h2>
			</div>
		</div>
	</div>
</section>
<section class="documentation centerContent">
	<div class="container">
		<div class="row description">
			<div class="col-md-3">
				<ul class="list-unstyled documentationMenu">
                    <li class="title">Getting Started</li>
                    <li class="item"><a href="<?=$boostack->getFriendlyUrl("docs/setup")?>">Setup</a>
                        <ul>
                            <li><a title="Server Requirements" href="<?=$boostack->getFriendlyUrl("docs/setup#ServerRequirements")?>">Server Requirements</a></li>
                            <li><a title="Installation" href="<?=$boostack->getFriendlyUrl("docs/setup#Installation")?>">Installation</a></li>
                            <li><a title="Automatic Configuration" href="<?=$boostack->getFriendlyUrl("docs/setup#AutomaticConfiguration")?>">Automatic Configuration</a></li>
                            <li><a title="Manual Configuration" href="<?=$boostack->getFriendlyUrl("docs/setup#ManualConfiguration")?>">Manual Configuration</a></li>
                            <li><a title="Friendly URLs Configuration" href="<?=$boostack->getFriendlyUrl("docs/setup#FriendlyURLsConfiguration")?>">Friendly URLs Configuration</a></li>
                            <li><a title="Accessing Configuration Values" href="<?=$boostack->getFriendlyUrl("docs/setup#AccessingConfigurationValues")?>">Accessing Configuration Values</a></li>
                            <li><a title="Development Mode" href="<?=$boostack->getFriendlyUrl("docs/setup#DevelopmentMode")?>">Development Mode</a></li>
                        </ul>
                    </li>
                    <li class="item"><a title="Directory structure" href="<?=$boostack->getFriendlyUrl("docs/directory-structure")?>">Directory structure</a></li>
                    <li class="title">Code</li>
                    <li class="item"><a title="Models" href="<?=$boostack->getFriendlyUrl("docs/models")?>">Models</a></li>
                    <li class="item"><a title="Controllers" href="<?=$boostack->getFriendlyUrl("docs/controllers")?>">Controllers</a></li>
                    <li class="item"><a title="Login Security" href="<?=$boostack->getFriendlyUrl("docs/loginSecurity#lockStrategies")?>">Login Security</a>
                        <ul>
                            <li><a title="Timer" href="<?=$boostack->getFriendlyUrl("docs/loginSecurity#Timer")?>">Timer</a></li>
                            <li><a title="Recaptcha" href="<?=$boostack->getFriendlyUrl("docs/loginSecurity#Recaptcha")?>">Google Recaptcha</a></li>
                        </ul>
                    </li>
			</div>
			<div class="col-md-9 documentationInnerContent">
                <?php
                $defaultPage = "template/boostack/documentation/setup.phtml";
                if(Request::hasQueryParam("docpath")) {
                    switch (Request::getQueryParam("docpath")) {
                        case "setup": {
                            require("template/boostack/documentation/setup.phtml");
                            break;
                        }
                        case "directory-structure": {
                            require("template/boostack/documentation/directory_structure.phtml");
                            break;
                        }
                        case "controllers": {
                            require("template/boostack/documentation/controllers.phtml");
                            break;
                        }
                        case "models": {
                            require("template/boostack/documentation/models.phtml");
                            break;
                        }
                        case "loginSecurity": {
                            require("template/boostack/documentation/loginSecurity.phtml");
                            break;
                        }
                        default: {
                            require($defaultPage);
                        }
                    }
                }
                else
                    require($defaultPage);
                ?>
            </div>
		</div>
	</div>
</section>