
<section class="disclaimer">
    <div class="line">
        <div class="container">
            <div class="row">
                <h1><span class="title">BOOSTACK</span> is a full stack web layer for PHP.<br/>
                    <span class="smaller">Improve your development and build a modern website in minutes</span></h1>
            </div>
            <div class="row text-center">
                <a href="<?=$boostack->url?>download" class="btn btn-lg download">Download Boostack</a>
            </div>
        </div>
    </div>
</section>

<section class="features">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2><span>Fast and Productive</span></h2>
                <p>
                    Boostack is a full stack web layer for PHP built for developers who need a simple layer to create
                    modern website in minutes.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Freedom</span></h2>
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                    doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                    veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Simplicity</span></h2>
                <p>
                    Boostack is a lightweight and flexible layer that provides a robust set of features
                    for web and mobile applications. Simple to configure, it contains JQuery and Bootstrap.
                </p>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-4">
                <h2><span>SEO Ready</span></h2>
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                    doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                    veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Extensible</span></h2>
                <p>
                    Import Boostack into your project and start coding.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Simplicity</span></h2>
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                    doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                    veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                </p>
            </div>
        </div>
    </div>
</section>