<section class="disclaimer sectionTitle">
	<div class="line">
		<div class="container">
			<div class="row">
				<h1><?=$boostack->getLabel("navigation.login");?></h1>
			</div>
		</div>
	</div>
</section>
<p>&nbsp;</p>
<section class="login centerContent">
	<div class="container">
		<div id="loginbox"
			class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
			<div class="panel panel-success">
				<div class="panel-heading">
					<div class="panel-title"><?=$boostack->getLabel("login.loggedin");?></div>
				</div>
				<div class="panel-body">

					<div class="text-center col-sm-12">
						<a class="btn btn-sm danger" href="<?=$boostack->getFriendlyUrl("logout")?>">Logout</a></div>
				</div>
			</div>
		</div>
	</div>
</section>