
<section class="disclaimer">
    <div class="line">
        <div class="container">
            <div class="row">
                <h1>
                    <span class="fadeInLeft animated"><span class="title">BOOSTACK</span> is a full stack web layer for PHP.</span><br/>
                    <span class="animated fadeInDown smaller">Improve your development and build a modern website in minutes</span>
                </h1>
            </div>
            <div class="row text-center animated fadeInUp">
                <a href="<?=$boostack->url?>download" class="btn btn-lg download">Download Boostack</a>
            </div>
        </div>
    </div>
</section>

<section class="features">
    <div class="container animated fadeIn">
        <div class="row">
            <div class="col-md-4">
                <h2><span>Fast and Productive</span></h2>
                <p>
                    Boostack is a full stack web layer for PHP <b>built for developers</b> who need a simple layer to create
                    modern website in minutes.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Freedom</span></h2>
                <p>
                    No framework, no naming conventions, <b>use your own coding and naming</b>.
                    Boostack is a minimal layer of code that lets you use your creativity.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Simplicity</span></h2>
                <p>
                    Boostack is a lightweight and flexible layer that provides a robust set of features
                    for <b>web and mobile applications</b>.
                </p>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-4">
                <h2><span>SEO Ready</span></h2>
                <p>
                    Boostack <b>integrate SEO features</b> for meta data: rich snippets, openGraph, internal linking,
                    schema markup, social media and more.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Extensible</span></h2>
                <p>
                    Create your project with Boostack and start coding. Extend all php classes and <b>build quickly</b>
                    simple or complex web-based apps.
                </p>
            </div>
            <div class="col-md-4">
                <h2><span>Secure</span></h2>
                <p>
                    Built on PHP - MySql - HTML5 - CSS3 - JQuery Boostack runs on secure and fast-loading code for <b>optimal performance</b>.
                </p>
            </div>
        </div>

        <div class="row text-center">
            <p>&nbsp;</p><p>&nbsp;</p>
            <h4>Simple to configure it. It contains JQuery, JQuery TE, Animate.css and Bootstrap.</h4>
            <a href="http://localhost/boostack/download" class="btn btn-lg download">Download Boostack</a>
        </div>
    </div>
</section>