<footer class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-4 copy">
                <b>Boostack</b> is licensed under <a href="https://github.com/offmania9/Boostack/blob/master/LICENSE" target="_blank">MIT</a>.
            </div>
            <div class="col-md-8 text-right">
                <? require("template/boostack/nav.phtml");?>
            </div>
        </div>
    </div>
</footer>

<!--
<div itemscope itemtype="http://schema.org/SoftwareApplication">

    <div class="row">
        <div class=" col-md-4 col-sm-3 hidden-xs col-lg-4"></div>
        <div class=" col-md-4 col-sm-3 hidden-xs col-lg-4"></div>
        <div class=" col-md-4 col-sm-3 hidden-xs col-lg-4"></div>
    </div>

</div>
<a title="Follow $boostack->sitename on Google+" href="$boostack->gplus" rel="publisher"></a>
<a title="Follow $boostack->sitename on Google+" target="_blank" href="$boostack->gplus?rel=author"></a>
<a title="Follow $boostack->sitename on Google+" href="$boostack->gplus" rel="me"></a>
-->