<footer class="container-fluid">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 copy">
				<b><?=$boostack->getLabel("projectName");?></b> <?=$boostack->getLabel("license");?>
            </div>
			<div class="col-md-8 col-xs-12 text-right">
                <?php require("template/boostack/nav.phtml");?>
            </div>
		</div>
	</div>
</footer>
<a title="Follow <?=Config::get("sitename");?> on Google+" href="<?=Config::get("gplus");?>" rel="publisher"></a>
<a title="Follow <?=Config::get("sitename");?> on Google+" target="_blank" href="<?=Config::get("gplus");?>?rel=author"></a>
<a title="Follow <?=Config::get("sitename");?> on Google+" href="<?=Config::get("gplus");?>" rel="me"></a>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-64045049-1', 'auto');ga('send', 'pageview');
</script>