<div class="container">
	<div class="row header">
		<div class="col-md-4 col-xs-12" itemscope itemtype="http://schema.org/SoftwareApplication">
			<a title="Boostack" class="brandlink" href="<?=$boostack->url;?>">
				<h1>
					<img itemprop="image" alt="<?=$boostack->getLabel("projectName");?>" title="<?=$boostack->getLabel("projectName");?>" src="<?=$boostack->registerImgFile('boostack_logo_xs2.png');?>" />
                    <span class="projectName" itemprop="name"><?=$boostack->getLabel("projectName");?></span>
                    <span style="display: none;" itemprop="applicationCategory">PHP Framework</span>
            	</h1>
			</a>
		</div>
		<div class="col-md-8 col-xs-12 text-right">
            <?php require("template/boostack/nav.phtml");?>
        </div>
	</div>
</div>