<div class="container">
	<div class="row header">
		<div class="col-md-4 col-xs-12">
			<a class="brandlink" href="<?=$boostack->url;?>">
				<h1>
					<img alt="" title="<?=$boostack->getLabel("projectName");?>" src="<?=$boostack->registerImgFile('boostack_logo_xs2.png');?>" />
                    <span class="projectName"><?=$boostack->getLabel("projectName");?></span>
            	</h1>
			</a>
		</div>
		<div class="col-md-8 col-xs-12 text-right">
            <?php require("template/boostack/nav.phtml");?>
        </div>
	</div>
</div>