<header>
	<ul>
		<li><a href="<?=$boostack->getFriendlyUrl("home");?>"><?=$boostack->getLabel("navigation.home");?></a></li>
		<li><a href="<?=$boostack->getFriendlyUrl("download");?>"><?=$boostack->getLabel("navigation.download");?></a></li>
		<li><a href="<?=$boostack->getFriendlyUrl("docs/introduction");?>"><?=$boostack->getLabel("navigation.documentation");?></a></li>
		<li><a href="<?=$boostack->getFriendlyUrl("login");?>"><?=$boostack->getLabel("navigation.login");?></a></li>
		<li><a href="<?=$boostack->getFriendlyUrl("registration");?>"><?=$boostack->getLabel("navigation.registration");?></a></li>
	</ul>
</header>
