<?php
use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Controllers</h2>
        <p>Controllers can be found in the root folder of the project.</p>
        <p>Ax example of default controllers provided by Boostack are <code>index.php</code> or <code>login.php</code></p>
        <p>To create a new controller, you can create a brand new file in the root folder of your project and follow the logic above:</p>
        <pre><code>&lt;?php
    require_once "core/environment_init.php";


    // INSERT HERE YOUR LOGIC


?&gt;</code></pre>

        <div class="col-md-3">
            <ul class="list-unstyled sticky-top small lh-lg">
                <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light d-none" title="" href="<?= Request::getFriendlyUrl("docs/setup#item") ?>">Item</a></li>
            </ul>
        </div>
    </div>