<?php

use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Controllers</h2>
        <p>You can organize your controllers inside the <b>My/Controllers</b> folder and call them within the pages located in the project's "public" folder.</p>
        <p>To create a new controller, you can create a brand new file in the My/Controllers folder of your project and follow the logic above:</p>
        <pre>&lt;?php
    namespace My\Controllers;

    class Course extends \My\Controller
    {
        public static function init()
        {
            echo "This is the courses page";
        }
    }
?&gt;</pre>

        <div class="col-md-3">
            <ul class="list-unstyled sticky-top small lh-lg">
                <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light d-none" title="" href="<?= Request::getFriendlyUrl("docs/setup#item") ?>">Item</a></li>
            </ul>
        </div>
    </div>