<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Course: Controller Example</h2>
        <section id="ControllerExample">
            <h3 class="">Course.php</h3>
            <p class="">
                Now you need to create your custom controller Course.php in the <b>My/Controllers</b> folder.</p>
            <p>
                For example, the Course.php file should look like this:
            <pre>&lt;?php
    namespace My\Controllers;

    class Course extends \My\Controller
    {
        public static function init()
        {
            echo "This is the courses page";
        }
    }
?&gt;</pre>
            </p>
        </section>
    </div>
    <div class="col-md-3">
    </div>
</div>