<?php

use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">CURL</h2>
        <p>
            <b>The CurlRequest class within the Boostack\Models\Curl namespace is designed to facilitate the management and execution of cURL requests in PHP.</b>
            It provides a series of methods that allow you to configure various aspects of the request, such as the endpoint URL, GET and POST fields, custom headers, request type (GET or POST), returning the transfer as a string, and the user agent. Once the necessary parameters are configured, the class allows you to send the request and obtain the response, thereby simplifying the interaction with external APIs or other web services.
        </p>

        <h4 id="Requirements">Requirements</h4>
        <p>In order to use PHP's cURL functions you need to install the » libcurl package.</p>

        <h4 id="UsageExample">
            Usage Example
        </h4>
        <pre>
$request = new CurlRequest();
$request->setEndpoint(Config::get("url")."/api/getLogList");
$request->setCustomHeader(array("Authorization: Bearer {[example api_key]}"));
$request->setPostFields(json_encode(array(
    'input' => $raw_content,
    'model' => $model
)));
$request->setContentTypeJSON(true);
$mb = $request->send();
</pre>

        <h4 id="Methods">Methods</h4>
        <ul>
            <li><code>CurlRequest::setEndpoint($endpoint)</code><br />
                Set the endpoint where make HTTP request to the cUrl.</li>
            <li><code>CurlRequest::setIsPost($isPost)</code><br />
                The method accept boolean value (true or false) in case your request is in POST method otherwise set into FALSE.</li>
            <li><code>CurlRequest::setReturnTransfer($returnTransfer)</code><br />
                Set TRUE to return the raw output</li>
            <li><code>CurlRequest::setGetFields($fields)</code><br />
                Set the method Get with their $fields</li>
            <li><code>CurlRequest::setPostFields($fields)</code><br />
                Set the field with POST method, This parameter can be passed as an array with the field name as key and field data as value.</li>
            <li><code>CurlRequest::setCustomHeader($data)</code><br />
                The headers specified in this parameter will be used in requests both to servers and proxies. Like An array of HTTP header fields to set, in the format array('Content-type: text/plain', 'Content-length: 100').</li>
            <li><code>CurlRequest::send()</code><br />
                Execute cUrl request, and the return data can be obtained using Class <code>MessageBag</code>. <br />
                The result if the cUrl request have success can be obtained by using method <code>getData</code>.<br />
                In case of error you can check the existing of error using method <code>hasError</code> and <code>getErrorMessage</code></li>
        </ul>
    </div>
    <div class="col-md-3">
        <ul class="list-unstyled sticky-top small lh-lg">
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Usage Example" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/curl#Requirements") ?>">Requirements</a></li>
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Usage Example" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/curl#UsageExample") ?>">Usage Example</a></li>
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Methods" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/curl#Methods") ?>">Methods</a></li>
        </ul>
    </div>
</div>