<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Course: First Example</h2>
        <section id="FirstExample">
            <h3 class="pt-3">Add path</h3>
            <p>
                Open the index.php and add a new route in <code>initRoutes()</code>:</p>
      <pre><code>$router->addRoute('course', [My\Controllers\Course::class, 'init']);</code></pre>
            </p>
            <h3 class="">Create controller: Course.php</h3>
            <p class="">
                Now you need to create your custom controller Course.php in the <b>My/Controllers</b> folder
            <pre>&lt;?php
    namespace My\Controllers;

    class Course extends \My\Controller
    {
        public static function init()
        {
            echo "This is the courses page";
        }
}?&gt;</pre>
            </p>
            Now you get "your-address/course" or e.g. "http://domain-name/course" and you can see "This is the courses page".
        </section>
    </div>
    <div class="col-md-3">
        
    </div>
</div>