<?php

use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Course: Model List Example</h2>

        <section id="Example">
            <p>
                Create a new PHP file named <code>CourseList.php</code> in the <code>my/Models/Courses folder</code>.
            </p>
            <p>
                For example, the <code>CourseList.php</code> file should look like this:
            <pre>&lt;?php
namespace My\Models\GDS;

use Boostack\Models\BaseList;
use My\Models\Courses\Course;

class CourseList extends BaseList
{
    const BASE_CLASS = Course::class;

    public function __construct()
    {
        parent::init();
    }
}
?&gt;</pre>
            </p>
            <p>In this simple example, the CourseList class will inherit all methods and functionalities from the BaseList class. You can extend the CourseList class to implement new methods and logic.</p>

        </section>

    </div>
    <div class="col-md-3">
        <ul class="list-unstyled sticky-top small lh-lg">
            
        </ul>
    </div>
</div>