<?php
use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Setup</h2>

        <section id="Download">
            <h3 class="pt-3">Download</h3>
            <h5>Via Composer/Packagist</h5>
            <p>
                <code>composer create-project offmania9/boostack</code>
                <br />
                <small>Import as vendor: <em>composer require offmania9/boostack</em></small>
            </p>
            <h5>or Via GIT Clone</h5>
            <p>
                <code>git clone https://github.com/offmania9/boostack.git</code>
            </p>
        </section>

        <section id="Installation">
            <h3 class="pt-3">Installation</h3>
            You can install Boostack using two distinct installation procedures:
            <ul>
                <li><b>[recommended] via Docker</b> which will install 3 containers (php-apache, maria db, phpmyadmin) including all the requirements necessary for the operation of Boostack. Jump to Docker Installation chapter.</li>
                <li>or as a <b>stand-alone</b> application within an Apache web application server
                    <div class="ps-5">
                        <p>General requirements</p>
                        <ul>
                            <li><code>PHP >= 7.4</code></li>
                            <li><code>PDO PHP Extension</code></li>
                        </ul>
                        <p>Apache modules enabled (httpd.conf):</p>
                        <ul>
                            <li>
                                <code>mod_rewrite</code>
                            </li>
                            <li>
                                <code>mod_headers</code>
                            </li>
                            <li>
                                <code>mod_filters</code>
                            </li>
                        </ul>
                        <p>Virtual host configuration:</p>
                        <pre class="smallx2">
    &lt;Directory /var/www/html&gt;
        Options FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    &lt;/Directory&gt;</pre>
                        <h6>Optimal Server Configuration</h6>
                        HTTP Strict Transport Security (HSTS) is an opt-in security enhancement that is specified by a web application through the use of a special response header. Once a supported browser receives this header that browser will prevent any communications from being sent over HTTP to the specified domain and will instead send all communications over HTTPS. It also prevents HTTPS click through prompts on browsers.
                    </div>
                </li>
            </ul>
        </section>


        <section id="InstallationDocker">
            <h3 class="pt-3">Docker Installation</h3>
            <p>Launch Docker compose in project root
                <br /><code>docker-compose up -d --build</code>
            </p>
            <p>In the Docker compose file, you need to comment out the user parameter for php-apache based on
                the operating system: 502:20 for macOS and 1000:1000 for Unix. Leave both lines commented out (disabled)
                in case of Windows operating systems.</p>
            <pre tabindex="0">
    php-apache:
    # user: "502:20" #-> MacOS
    # user: "1000:1000" #-> Unix
        </pre>
            <p class="text-end">
                Jump to <a class="fw-bold " href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/first-configuration") ?>">First Configuration &#8594;</a>
            </p>
        </section>
    </div>
    <div class="col-md-3">
        <ul class="list-unstyled sticky-top small lh-lg">
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Download" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/setup#Download") ?>">Download</a></li>
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Installation" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/setup#Installation") ?>">Installation</a></li>
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Installation Docker" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/setup#InstallationDocker") ?>">Docker Installation</a></li>
        </ul>
    </div>
</div>