<?php

use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Users</h2>
        <p><b>The <code>User</code> class can be used to create, view or edit user instances</b>. It is a <b>Proxy class</b> that provides a unified interface to access information on the other user sub-classes.<br/>
        The sub-classes are: 
        <ul>
            <li><code>User_Entity</code></li>
            <li><code>User_Social</code></li>
            <li><code>User_Registration</code></li>
            <li><code>User_Info</code></li>
        </ul>
        </p>

        <h4 id="UsageExample">
            Usage Example
        </h4>
        <pre>
$u = new User();
$u->username = "boostack";
$u->name = "Boostack System";
$u->email = "system@getboostack.com";
$u->pwd = "testing";
$u->privilege = "0";
$u->first_name = "Boostack";
$u->company = "Boostack";
$u->last_name = "System";
$u->save();// new user registration

$u = new User([id of an existing user]);
$u->name = "New Name ";
$u->save();// update user data
</pre>
<p>Use the <a href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/auth") ?>">Auth</a> class to manage login and logout for the current user.</p>

        <h4 id="Methods">Methods</h4>
        <ul>
            <li><code>fill($array)</code><br />
                The method fill the user object with array of key-value.</li>
            <li><code>load($id)</code><br />
                This method Assign the ID passed as parameter to the User id and wait for other method to execute.</li>
            <li><code>save($forcedID)</code><br />
                The method save user data into database by a <code>Transaction</code>. If there is a parameter ID the method invoke the save method of all under instance, otherwise save with incremental id from database and save under instance with the same id.</li>
            <li><code>delete()</code><br />
                This method is used to remove the user data from the under instance of user object.</li>
            <li><code>jsonSerialize()</code><br />
                Return an array of User object from under Instance.</li>
            <li><code>User::existById($id, $throwException)</code>
                <br />Check with id parameter the existence of user on the database.
            </li>
            <li><code>User::existsByEmail($email, $throwException)</code><br />
                Check with email parameter the existence of user on the database.</li>
            <li><code>User::existsByUsername($username, $throwException)</code><br />
                Check with username parameter the existence of user on the database.</li>
            <li><code>User::getUserIDByEmail($email, $throwException)</code><br />
                Return the User Id from Email parameter.</li>
            <li><code>User::getCredentialByCookie($cookieValue)</code><br />
                Return username and password by cookie parameter.</li>
            <li><code>User::getActiveCredentialByEmail($email)</code><br />
                Return id and password by email parameter.</li>
            <li><code>User::getActiveCredentialByUsername($username)</code><br />
                Return id and password by username parameter.</li>
            <li><code>User::getActiveCredentialByEmailOrUsername($email, $username)</code><br />
                Return id and password by email or username parameter.</li>
            <li><code>User::getActiveIdByEmailAndPassword($email, $password)</code><br />
                Return id by email or password parameter.</li>
            <li><code>User::getActiveIdByUsernameAndPassword($username, $password)</code><br />
                Return id by username or password parameter.</li>
            <li><code>User::getActiveIdByEmailOrUsernameAndPassword($email, $username, $password)</code><br />
                Return id by email or username or password parameter.</li>
            <li><code>refreshRememberMeCookie()</code><br />
                set cookie with updated cookie value.</li>
        </ul>
        <br />

        <h4 id="List">List</h4>
        <p>You can use <code>UserList</code> class to handle multiple user instances.</p>
        <ul>
            <li><code>loadAll()</code><br />
                Perform all item about user.</li>
            <li><code>view($fields, $orderColumn, $orderType, $numitem, $currentPage)</code><br />
                View method is used to render a list of user item with filter and pagination.</li>
            <li><code>fill($array, $excludePwd)</code><br />
                The fill method perform load of a single item and create the user object defined in <code>User</code> class.</li>
            <li><code>getSQLFromJoinPart()</code><br />
                This method used to perform a join of other table with User main table.</li>
        </ul>
    </div>
    <div class="col-md-3">
        <ul class="list-unstyled sticky-top small lh-lg">
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Usage Example" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/users#UsageExample") ?>">Usage Example</a></li>
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Methods" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/users#Methods") ?>">Methods</a></li>
            <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light" title="Methods" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/users#List") ?>">List</a></li>
        </ul>
    </div>
</div>