<?php

use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2 class="fw-bold">Views</h2>
        <section>
            <p>All Views are implemented in <b>.phtml</b> files and organized in the <b>Views/templates</b> folder. <br />
                Additionally, you can make views modular by dividing their content into smaller .phtml files (partials) stored in the <b>Views/templates/partials</b> folder.
            </p>

            <p>For example, the Views/templates folder can contain an <b>index.phtml</b> file that includes other .phtml files from the "partials" folder.</p>
            <pre>&lt;?php require "partials/before_content.phtml"; // Pre-content code that can be shared across all pages ?&gt;
&lt;?php require "partials/header.phtml"; // Header code that can be shared across all pages ?&gt;
&lt;?php require "partials/index.phtml";  // Custom code for the specific index page ?&gt;
&lt;?php require "partials/footer.phtml"; // Footer code that can be shared across all pages ?&gt;
&lt;?php require "partials/after_content.phtml";  // Closing code that can be shared across all pages ?&gt;
</pre>
        </section>

        <section id="ControllerUpdate">
            <h3 class="pt-3">Controller Update</h3>
            <p class="">
                To utilize views, you can use the render method of the View class in the Boostack framework.
            </p>
            <p class="">
                For example, you can update the respective controller in the my/Controllers folder to use the render method as follows:
            </p>
            <pre>&lt;?php
namespace My\Controllers;

use Boostack\Views\View;

class Index extends \My\Controller
{
    public static function init()
    {
        // If you just need to render your template use this function
        View::render("yourViewTemplate.phtml");
        // If you need variable on your template you can use array parameter into template render function
        View::render("yourViewTemplate.phtml", array(
            "key" => value,
            "key" => value
            ));
    }
}
?&gt;</pre>

            <p class="">
                The View::render("yourViewTemplate.phtml") method will automatically load the yourViewTemplate.php file located in my/Views/templates.
            </p>
        </section>


        <section id="Example">
            <h3 class="pt-3">Example</h3>
            <p class="text-end">
                Jump to <a class="fw-bold " href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/view-example") ?>">View Example &#8594;</a>
            </p>
        </section>

        <div class="col-md-3">
            <ul class="list-unstyled sticky-top small lh-lg">
                <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light d-none" title="" href="<?= Request::getFriendlyUrl("docs/setup#item") ?>">Item</a></li>
            </ul>
        </div>
    </div>