<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h1><?= Language::getLabel("error.attention"); ?></h1>
            </div>
        </div>
    </div>
</section>

<section class="download centerContent">
    <div class="container">
        <div class="row description">
            <h2><?= Language::getLabel("error.urlnotfound"); ?></h2>
            <p>
                <a href="<?= Config::get("url"); ?>"><?= Config::get("url"); ?></a>
            </p>
        </div>
    </div>
</section>