<header>
	<ul>
		<li>
            <a title="Home" href="<?= Template::getFriendlyUrl("home"); ?>"><?= Language::translate("navigation.home"); ?></a>
        </li>
		<li>
            <a title="Download" href="<?= Template::getFriendlyUrl("download"); ?>"><?= Language::translate("navigation.download"); ?></a>
        </li>
		<li>
            <a title="Documentation" href="<?= Template::getFriendlyUrl("docs/setup"); ?>"><?= Language::translate("navigation.documentation"); ?></a>
        </li>
		<li>
            <a title="Login" href="<?= Template::getFriendlyUrl("login"); ?>"><?= Language::translate("navigation.login"); ?></a>
        </li>
		<li>
            <a title="Registration" href="<?= Template::getFriendlyUrl("registration"); ?>"><?= Language::translate("navigation.registration"); ?></a>
        </li>
	</ul>
</header>
