<header>
	<ul>
		<li>
            <a title="Home" href="<?= Utils::getFriendlyUrl("home"); ?>"><?= Language::getLabel("navigation.home"); ?></a>
        </li>
		<li>
            <a title="Download" href="<?= Utils::getFriendlyUrl("download"); ?>"><?= Language::getLabel("navigation.download"); ?></a>
        </li>
		<li>
            <a title="Documentation" href="<?= Utils::getFriendlyUrl("docs/setup"); ?>"><?= Language::getLabel("navigation.documentation"); ?></a>
        </li>
		<li>
            <a title="Login" href="<?= Utils::getFriendlyUrl("login"); ?>"><?= Language::getLabel("navigation.login"); ?></a>
        </li>
		<li>
            <a title="Registration" href="<?= Utils::getFriendlyUrl("registration"); ?>"><?= Language::getLabel("navigation.registration"); ?></a>
        </li>
        <?php if (Utils::hasPrivilege(Auth::getUserLoggedObject(), PRIVILEGE_SUPERADMIN)): ?>
            <li><a title="Log" href="<?= Utils::getFriendlyUrl("log"); ?>"><?= Language::getLabel("navigation.log"); ?></a></li>
        <? endif; ?>
	</ul>
</header>
