<div class="row">
    <div class="col-md-9">
        <h2>Logs</h2>
        <p>Boostack log provides an easy way to store system messages.<br /></p>
        <h4>Levels</h4>
        <p>Is composed by several levels:</p>
        <ul>
            <li><code>Log_Level::ERROR</code></li>
            <li><code>Log_Level::WARNING</code></li>
            <li><code>Log_Level::FAILURE</code></li>
            <li><code>Log_Level::INFORMATION</code></li>
            <li><code>Log_Level::SUCCESS</code></li>
            <li><code>Log_Level::CRONJOB</code></li>
        </ul>

        <h4>Types</h4>
        <p>There are two types of log types:</p>
        <ul>
            <li><code>Log_Driver:FILE</code></li>
            <li><code>Log_Driver:DATABASE</code></li>
        </ul>

        <h4>Use</h4>
        <pre><code>Logger::write($message, $level, $type)</code></pre><br />

        <h4>List</h4>
        <p>You can also use <code>Log_Database_List</code> class to view list of your log.</p>
        <div class="col-md-3">
            <ul class="list-unstyled sticky-top small lh-lg">
                <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light d-none" title="" href="<?= Utils::getFriendlyUrl("docs/setup#item") ?>">Item</a></li>
            </ul>
        </div>
    </div>