        <?php if (Config::get('session_on') && Config::get('csrf_on')) : ?>
            <?= Session::CSRFRenderHiddenField(); ?>
        <?php endif; ?>
        <script type="text/javascript">
            var rootUrl = "<?= Config::get("url") ?>";
            var developmentMode = "<?= Config::get('developmentMode') ?>";
        </script>
        <?php Template::renderDefaultJSFiles(); ?>
        <?php Template::renderCustomJSFiles(); ?>
        </body>
        </html>