<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2 class="text-white textShadow display-4"><?= Language::getLabel("navigation.log"); ?>
                    <span class="small">Super Admin</span>
                </h2>
            </div>
        </div>
    </div>
</section>
<section class="logList centerContent py-3">
    <div class="container">
        <div class="mx-auto col-md-8 small">
            <?php d($logList); ?>
        </div>
    </div>
</section>