<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2 class="text-white textShadow display-4"><?= Language::getLabel("navigation.documentation"); ?></h2>
            </div>
        </div>
    </div>
</section>
<section class="documentation centerContent py-5 fw-light">
    <div class="container">
        <div class="row description">
            <div class="col-md-3">
                <ul class="list-unstyled documentationMenu sticky-top">
                    <li class="title fw-bold pt-2">Getting Started</li>
                    <li class="ps-3">
                        <a class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/setup") ?>">Setup</a>
                    </li>
                    <li class="ps-3">
                        <a class="link-opacity-75-hover link-underline-light fw-normal" title="Directory structure" href="<?= Utils::getFriendlyUrl("docs/directory-structure") ?>">Directory structure</a>
                    </li>
                    <li class="title fw-bold pt-3">Architecture</li>
                    <li class="ps-3">
                        <a title="Models" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/models") ?>">Models</a>
                    </li>
                    <li class="ps-3">
                        <a title="Controllers" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/controllers") ?>">Controllers</a>
                    </li>
                    <li class="ps-3">
                        <a title="Template" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/template") ?>">Template</a>
                    </li>
                    <li class="title fw-bold pt-3">Utilities</li>
                    <li class="ps-3">
                        <a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/auth") ?>">Auth</a>
                    </li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/loginSecurity") ?>">Lock Strategies</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/users") ?>">Users</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/session") ?>">Session</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/curl") ?>">CURL</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/log") ?>">Log</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Utils::getFriendlyUrl("docs/validator") ?>">Validator</a></li>
            </div>
            <div class="col-md-9 documentationInnerContent">
                <?php
                $defaultPage = "documentation/setup.phtml";
                if (Request::hasQueryParam("docpath")) {
                    switch (Request::getQueryParam("docpath")) {
                        case "setup": {
                                require "documentation/setup.phtml";
                                break;
                            }
                        case "directory-structure": {
                                require "documentation/directory_structure.phtml";
                                break;
                            }
                        case "controllers": {
                                require "documentation/controllers.phtml";
                                break;
                            }
                        case "models": {
                                require "documentation/models.phtml";
                                break;
                            }
                        case "loginSecurity": {
                                require "documentation/loginSecurity.phtml";
                                break;
                            }
                        case "template": {
                                require "documentation/template.phtml";
                                break;
                            }
                        case "auth": {
                                require "documentation/auth.phtml";
                                break;
                            }
                        case "users": {
                                require "documentation/users.phtml";
                                break;
                            }
                        case "session": {
                                require "documentation/session.phtml";
                                break;
                            }
                        case "curl": {
                                require "documentation/curl.phtml";
                                break;
                            }
                        case "log": {
                                require "documentation/log.phtml";
                                break;
                            }
                        case "validator": {
                                require "documentation/validator.phtml";
                                break;
                            }
                        default: {
                                require $defaultPage;
                            }
                    }
                } else
                    require $defaultPage;
                ?>
            </div>
        </div>
    </div>
</section>