<footer class="container-fluid">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 copy">
				<b><?= Language::getLabel("projectName"); ?></b> <?= Language::getLabel("license"); ?>
            </div>
			<div class="col-md-8 col-xs-12 text-end">
                <?php require "nav.phtml"; ?>
            </div>
		</div>
	</div>
</footer>
<a title="Follow <?= Config::get("sitename"); ?> on Google+" href="<?= Config::get("gplus"); ?>" rel="publisher"></a>
<a title="Follow <?= Config::get("sitename"); ?> on Google+" target="_blank" href="<?= Config::get("gplus"); ?>?rel=author"></a>
<a title="Follow <?= Config::get("sitename"); ?> on Google+" href="<?= Config::get("gplus"); ?>" rel="me"></a>
