<div class="container">
	<div class="row header">
		<div class="col-md-4 col-xs-12" itemscope itemtype="http://schema.org/SoftwareApplication">
			<a title="Boostack" class="brandlink" href="<?= Config::get("url"); ?>">
				<h1>
					<img itemprop="image" class="rounded" alt="<?= Language::getLabel("projectName"); ?> main logo" src="<?= Template::getImageLink("boostack_logo_xs2.png"); ?>" />
                    <span class="projectName" itemprop="name"><?= Language::getLabel("projectName"); ?></span>
                    <span style="display: none;" itemprop="applicationCategory">PHP Framework</span>
            	</h1>
			</a>
		</div>
		<div class="col-md-8 col-xs-12 text-end">
            <?php require "nav.phtml"; ?>
        </div>
	</div>
</div>