<section class="disclaimer">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2 class="p-3 pb-0 p-lg-5 pb-lg-3 textShadow text-center fw-light text-white">
                    <span class="fadeInLeft animated display-4">
                        <span class="text-dark textShadow-none"><?= Language::getLabel("projectName"); ?></span>
                        <?= Language::getLabel("mainDescription"); ?></span>
                    <br />
                    <p class="animated fadeInDown small lh-sm pt-3"><?= Language::getLabel("mission"); ?></p>
                </h2>
            </div>
            <div class="row text-center animated fadeInUp pb-4">
                <a title="Download Boostack" href="<?= Utils::getFriendlyUrl("download") ?>" class="btn btn-lg my-4 btn-outline-light p-3 download mx-auto w-auto px-5"><?= Language::getLabel("downloadBoostack"); ?> <?= Config::get("project_version"); ?></a>
            </div>
        </div>
    </div>
</section>
<section class="features py-4">
    <div class="container animated fadeIn">
        <div class="row">
            <div class="col-md-12 pb-4 pt-3">
                <div class="row">
                    <div class="col-md-4">
                        <h3 class="text-center pb-3">
                            <span class="underline-primary"><?= Language::getLabel("featuresTitles.fast"); ?></span>
                        </h3>
                        <p class="fw-light">
                            <?= Language::getLabel("featuresDescriptions.fast"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3 class="text-center pb-3">
                            <span class="underline-primary"><?= Language::getLabel("featuresTitles.freedom"); ?></span>
                        </h3>
                        <p class="fw-light">
                            <?= Language::getLabel("featuresDescriptions.freedom"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3 class="text-center pb-3">
                            <span class="underline-primary"><?= Language::getLabel("featuresTitles.simplicity"); ?></span>
                        </h3>
                        <p class="fw-light">
                            <?= Language::getLabel("featuresDescriptions.simplicity"); ?>
                        </p>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-4">
                        <h3 class="text-center pb-3">
                            <span class="underline-primary"><?= Language::getLabel("featuresTitles.seo"); ?></span>
                        </h3>
                        <p class="fw-light">
                            <?= Language::getLabel("featuresDescriptions.seo"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3 class="text-center pb-3">
                            <span class="underline-primary"><?= Language::getLabel("featuresTitles.extensible"); ?></span>
                        </h3>
                        <p class="fw-light">
                            <?= Language::getLabel("featuresDescriptions.extensible"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3 class="text-center pb-3">
                            <span class="underline-primary"><?= Language::getLabel("featuresTitles.secure"); ?></span>
                        </h3>
                        <p class="fw-light">
                            <?= Language::getLabel("featuresDescriptions.secure"); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="row text-center py-4">
            <div class="col-md-6 mx-auto">
                <p>
                <h4 class="fw-light"><?= Language::getLabel("inclusions") ?></h4>
                <h5><?= Language::getLabel("inclusions2") ?></h5>
                </p>
            </div>
            <div class="col-md-6 mx-auto">
                <p>
                    <a title="Download Boostack" href="<?= Utils::getFriendlyUrl("download") ?>" 
                    class="btn btn-lg my-4 btn-outline-dark p-3 download mx-auto w-100 px-5"><?= Language::getLabel("downloadBoostack"); ?> <?= Config::get("project_version"); ?></a>
                </p>
            </div>
        </div>
    </div>
</section>