<section class="disclaimer">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2 class="p-3 pb-0 p-lg-5 pb-lg-3">
                    <span class="fadeInLeft animated">
                        <span class="title"><?= Language::getLabel("projectName"); ?></span>
                        <?= Language::getLabel("mainDescription"); ?></span>
                    <br />
                    <p class="animated fadeInDown smaller lh-sm pt-3"><?= Language::getLabel("mission"); ?></p>
                </h2>
            </div>
            <div class="row text-center animated fadeInUp pb-4">
                <a title="Download Boostack" href="<?= Utils::getFriendlyUrl("download") ?>" 
                class="btn btn-lg my-4 btn btn-outline-light text-light p-3 download mx-auto w-auto px-5"><?= Language::getLabel("downloadBoostack"); ?> <?= Config::get("project_version"); ?></a>
            </div>
        </div>
    </div>
</section>
<section class="features">
    <div class="container animated fadeIn">
        <div class="row">
            <div class="col-md-12 pb-4 pt-3">
                <div class="row">
                    <div class="col-md-4">
                        <h3>
                            <span><?= Language::getLabel("featuresTitles.fast"); ?></span>
                        </h3>
                        <p>
                            <?= Language::getLabel("featuresDescriptions.fast"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3>
                            <span><?= Language::getLabel("featuresTitles.freedom"); ?></span>
                        </h3>
                        <p>
                            <?= Language::getLabel("featuresDescriptions.freedom"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3>
                            <span><?= Language::getLabel("featuresTitles.simplicity"); ?></span>
                        </h3>
                        <p>
                            <?= Language::getLabel("featuresDescriptions.simplicity"); ?>
                        </p>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-4">
                        <h3>
                            <span><?= Language::getLabel("featuresTitles.seo"); ?></span>
                        </h3>
                        <p>
                            <?= Language::getLabel("featuresDescriptions.seo"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3>
                            <span><?= Language::getLabel("featuresTitles.extensible"); ?></span>
                        </h3>
                        <p>
                            <?= Language::getLabel("featuresDescriptions.extensible"); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h3>
                            <span><?= Language::getLabel("featuresTitles.secure"); ?></span>
                        </h3>
                        <p>
                            <?= Language::getLabel("featuresDescriptions.secure"); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="row text-center">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <div class="col-md-6 mx-auto">
                <p>
                <h4><?= Language::getLabel("inclusions") ?></h4>
                <h5><?= Language::getLabel("inclusions2") ?></h5>
                </p>
            </div>


            <div class="col-md-6 mx-auto">
                <p>
                    <a title="Download Boostack" href="<?= Utils::getFriendlyUrl("download") ?>" class="btn btn-lg download col-md-12 mx-auto"><?= Language::getLabel("downloadBoostack"); ?> <?= Config::get("project_version"); ?></a>
                </p>
            </div>
        </div>
    </div>
</section>