<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2><?= Language::getLabel("navigation.login");?></h2>
            </div>
        </div>
    </div>
</section>
<p>&nbsp;</p>
<section class="login centerContent">
    <div class="container">
        <div id="loginbox"
             class="col-md-6 mx-auto">
            <div class="card card-success border-success">
                <div class="card-header">
                    <div class="card-title text-center"><?= Language::getLabel("login.loggedin");?></div>
                </div>
                <div class="card-body">
                    <div class="text-center col-sm-12">
                        <a class="btn btn-outline-dark btn-sm" href="<?= Utils::getFriendlyUrl("logout")?>">Logout</a></div>
                </div>
            </div>
        </div>
    </div>
</section>