<?php
$ptitle = !empty($pageTitle) ? $pageTitle . " | " . Config::get('site_title') : Config::get('site_title');
$pdescription = !empty($pdescription) ? $pdescription : Config::get('site_description') . " - " . strtoupper($pageTitle) . " " . Language::getLabel("lang_code");
$pimage = !empty($image_src) ? $image_src : Config::get('url') . Config::get('url_logo');
?>
<!DOCTYPE html>
<html lang="<?= Language::getLabel("lang_code") ?>">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="<?= Config::get('viewport') ?>" />
<?php if (Config::get('facebookMetaTag')) { ?>
    <meta property="og:title" content="<?= $ptitle ?>" />
    <meta property="og:type" content="<?= Config::get('og_type') ?>" />
    <meta property="og:url" content="<?= $canonical ?>" />
    <meta property="og:image" content="<?= $pimage ?>" />
    <meta property="og:description" content="<?= $pdescription ?>" />
    <?php if (Config::get('fb_app_id') != "") { ?>
        <meta property="fb:app_id" content="<?= Config::get('fb_app_id') ?>" />
        <meta property="fb:admins" content="<?= Config::get('fb_admins') ?>" />
    <?php } ?>
<?php } ?>
    <meta name="twitter:card" content="<?= Config::get("twitter_card") ?>" />
    <meta name="twitter:site" content="<?= Config::get("twitter_site") ?>" />
    <meta name="twitter:title" content="<?= $ptitle ?>" />
    <meta name="twitter:description" content="<?= $pdescription ?>" />
    <meta name="twitter:image" content="<?= $pimage ?>" />
    <title><?= $ptitle ?></title>
    <meta name="description" content="<?= $pdescription ?>" />
    <meta name="author" content="<?= Config::get('site_author') ?>" />
    <meta content="<?= Config::get('site_keywords'); ?>" name="Keywords" />
    <meta content="INDEX, FOLLOW" name="ROBOTS" />
    <link rel="shortcut icon" href="<?= Config::get('url') . Config::get('site_shortcuticon'); ?>" />
    <link rel="image_src" href="<?= $pimage ?>" />
    <link rel="canonical" href="<?= $canonical ?>" />
    <base href="<?= Config::get('url') ?>" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <?php Template::renderDefaultCSSFiles_critical(); ?>
    <?php Template::renderJSFile("lib/jquery.js"); ?>
</head>

<body class="<?= isset($bodyClasses) ? $bodyClasses : '' ?>">
    <?php Template::renderDefaultCSSFiles_nonCritical(); ?>

    <?php if(Config::get('checkIfSetupFolderExists') && is_dir(ROOTPATH."setup")): ?>
        <?php require "setup_exists_header.phtml"; ?>
    <?php endif; ?>