<section class="disclaimer sectionTitle">
    <div class="line">
        <div class="container">
            <div class="row">
                <h2><?= Language::getLabel("navigation.registration"); ?></h2>
            </div>
        </div>
    </div>
</section>
<p>&nbsp;</p>
<section class="registration">
    <div class="container">
        <div class="col-md-6 mx-auto">
            <div class="card panel-default">
                <div class="card-header">
                    <h3 class="card-title">Registration</h3>
                </div>
                <div class="card-body">
                        <div class="text-right">
                            <small> <a href="<?= Utils::getFriendlyUrl("login");?>">
                                    <?= Language::getLabel("form.login.signin");?>
                                </a>
                            </small>
                        </div>
                    <div class="alert alert-danger col-sm-12 <?= $registrationError == "" ? "d-none" : "" ?>"><?= $registrationError; ?></div>
                    <form id="registration-form" class="form-horizontal" method="post" action="<?= Utils::getFriendlyUrl("registration"); ?>">
                        <div class="form-group">
                            <label for="inputEmail3" class="control-label">Email</label>
                            <div class="">
                                <input type="email" class="form-control" name="email" id="reg-email" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword1" class="ontrol-label">Password</label>
                            <div class="">
                                <input type="password" class="form-control" name="psw1" id="reg-pwd1" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword2" class="control-label">Repeat Password</label>
                            <div class="">
                                <input type="password" class="form-control" name="psw2" id="reg-pwd2" placeholder="Password">
                            </div>
                        </div>
                        <p id="form-validation-error" class="text-danger"></p>
                        <div class="form-group ">
                            <div class="">
                                <button type="submit" class="btn btn-dark ">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


