<div class="alert alert-danger alert-dismissible position-absolute fade show" style="z-index: 9999999;" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <div class="small">
        <p class="lead"><b>ATTENTION!</b> You <b>MUST</b> ensure you remove the entire <b><em>setup/</em></b> directory. Leaving the setup directory in place is a very
            serious potential security issue which may lead to deletion or alteration of files, etc.
            Please note that until this directory is removed, Boostack will not operate and a warning message will be displayed.
        </p>
    </div>
</div>