<?php

use Boostack\Models\Language;
use Boostack\Models\Request;
?>
<section class="disclaimer sectionTitle">
    <div class="line py-2">
        <div class="container">
            <div class="row">
                <h2 class="text-white textShadow display-6 mb-0"><?= Language::getLabel("navigation.documentation"); ?></h2>
            </div>
        </div>
    </div>
</section>
<section class="documentation centerContent pb-5 pt-4 fw-light">
    <div class="container small">
        <div class="row description">
            <div class="col-md-3">
                <ul class="list-unstyled documentationMenu sticky-top">
                    <?php

                    foreach ($all_items['categories'] as $category) {
                        echo '<li class="title fw-bold pt-2">' . htmlspecialchars($category['title']) . '</li>';
                        foreach ($category['items'] as $item) {
                            $classes = 'link-opacity-75-hover link-underline-light fw-normal';
                            if (strpos($item['title'], 'Example') !== false) {
                                $classes .= 'text-dark-green fw-bold';
                            }
                            echo '<li class="ps-3">';
                            echo '<a class="' . $classes . '" href="' . htmlspecialchars(Request::getFriendlyUrl("docs/" . $currentVersion . "/" . $item['path'])) . '">' . htmlspecialchars($item['title']) . '</a>';
                            echo '</li>';
                        }
                    }
                    ?>
                    <li class="title fw-bold pt-3 d-none">Examples</li>
                    <li class="ps-3 d-none">
                        <a title="first complete example d-none" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/first-complete-example") ?>">First complete example</a>
                    </li>
                    <li class="ps-3 d-none">
                        <a title="login example" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/login-example") ?>">Login example</a>
                    </li>
                    <li class="ps-3 d-none">
                        <a title="api example" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/" . $currentVersion . "/api-example") ?>">API example</a>
                    </li>
            </div>
            <div class="col-md-9 documentationInnerContent">
                <?php
                require "documentation_" . $currentVersion . "/" . $partial_filename;
                ?>
            </div>
        </div>
    </div>
</section>