<?php
use Boostack\Models\Language;
use Boostack\Models\Request;
?>
<section class="disclaimer sectionTitle">
    <div class="line py-2">
        <div class="container">
            <div class="row">
                <h2 class="text-white textShadow display-6 mb-0"><?= Language::getLabel("navigation.documentation"); ?></h2>
            </div>
        </div>
    </div>
</section>
<section class="documentation centerContent pb-5 pt-4 fw-light">
    <div class="container">
        <div class="row description">
            <div class="col-md-3">
                <ul class="list-unstyled documentationMenu sticky-top">
                    <li class="title fw-bold pt-2">Getting Started</li>
                    <li class="ps-3">
                        <a class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/setup") ?>">Setup</a>
                    </li>
                    <li class="ps-3">
                        <a class="link-opacity-75-hover link-underline-light fw-normal" title="Directory structure" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/directory-structure") ?>">Directory structure</a>
                    </li>
                    <li class="title fw-bold pt-3">Architecture</li>
                    <li class="ps-3">
                        <a title="Models" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/models") ?>">Models</a>
                    </li>
                    <li class="ps-3">
                        <a title="Controllers" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/controllers") ?>">Controllers</a>
                    </li>
                    <li class="ps-3">
                        <a title="Template" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/template") ?>">Template</a>
                    </li>
                    <li class="title fw-bold pt-3">Utilities</li>
                    <li class="ps-3">
                        <a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/auth") ?>">Auth</a>
                    </li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/loginSecurity") ?>">Lock Strategies</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/users") ?>">Users</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/session") ?>">Session</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/curl") ?>">CURL</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/log") ?>">Log</a></li>
                    <li class="ps-3"><a title="" class="link-opacity-75-hover link-underline-light fw-normal" href="<?= Request::getFriendlyUrl("docs/".$currentVersion."/validator") ?>">Validator</a></li>
            </div>
            <div class="col-md-9 documentationInnerContent">
                <?php
                $defaultPage = "documentation_".$currentVersion."/setup.phtml";
                if (Request::hasQueryParam("docpath")) {
                    switch (Request::getQueryParam("docpath")) {
                        case "setup": {
                                require "documentation_".$currentVersion."/setup.phtml";
                                break;
                            }
                        case "directory-structure": {
                                require "documentation_".$currentVersion."/directory_structure.phtml";
                                break;
                            }
                        case "controllers": {
                                require "documentation_".$currentVersion."/controllers.phtml";
                                break;
                            }
                        case "models": {
                                require "documentation_".$currentVersion."/models.phtml";
                                break;
                            }
                        case "loginSecurity": {
                                require "documentation_".$currentVersion."/loginSecurity.phtml";
                                break;
                            }
                        case "template": {
                                require "documentation_".$currentVersion."/template.phtml";
                                break;
                            }
                        case "auth": {
                                require "documentation_".$currentVersion."/auth.phtml";
                                break;
                            }
                        case "users": {
                                require "documentation_".$currentVersion."/users.phtml";
                                break;
                            }
                        case "session": {
                                require "documentation_".$currentVersion."/session.phtml";
                                break;
                            }
                        case "curl": {
                                require "documentation_".$currentVersion."/curl.phtml";
                                break;
                            }
                        case "log": {
                                require "documentation_".$currentVersion."/log.phtml";
                                break;
                            }
                        case "validator": {
                                require "documentation_".$currentVersion."/validator.phtml";
                                break;
                            }
                        default: {
                                require $defaultPage;
                            }
                    }
                } else
                    require $defaultPage;
                ?>
            </div>
        </div>
    </div>
</section>