<?php

use Boostack\Models\Language;
use Boostack\Views\View;
?>
<section class="disclaimer sectionTitle">
	<div class="line py-2">
		<div class="container">
			<div class="row">
				<h2 class="text-white textShadow display-4"><?= Language::getLabel("navigation.download"); ?></h2>
			</div>
		</div>
	</div>
</section>

<section class="download centerContent py-5 fw-light">
	<div class="container">
		<div class="row description centerContent">
			<div class="col">
				<h3><?= Language::getLabel("download.howto"); ?></h3>
				<p>
					<?= Language::getLabel("download.howtoDescription"); ?>
				<div class="text-start">
					<picture>
						<source srcset="<?= View::getImageLink("boostack_docs_repos.webp") ?>" type="image/webp">
						<img src="<?= View::getImageLink("boostack_docs_repos.jpg") ?>" alt="Boostack Repositories" class="mx-auto w-50" />
					</picture>
				</div>
				</p>
				<h3><?= Language::getLabel("download.downloadit"); ?></h3>
				<p>
					<?= Language::getLabel("download.downloaditDescription"); ?>
				</p>

				<h3><?= Language::getLabel("download.after"); ?></h3>
				<p>
					<?= Language::getLabel("download.afterDescription"); ?>
				</p>
			</div>
		</div>
	</div>
</section>