<?php
use Boostack\Models\Language;
?>
<footer class="container-fluid py-5 bg-light fw-light">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-xs-12 copy">
				<b><?= Language::getLabel("projectName"); ?></b> <?= Language::getLabel("license"); ?>
            </div>
			<div class="col-md-8 col-xs-12 text-end">
                <?php require "nav.phtml"; ?>
            </div>
		</div>
	</div>
</footer>