<?php
if (!empty($_POST)) { ?>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-md-8">
                <p>&nbsp;</p>
                <?php if (!empty($finalSetupMessageError)) { ?>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <h3>Attention!</h3>
                        <p class="lead"><?php echo $finalSetupMessageError ?></p>
                        <p class="lead" class="text-start"><b><a href="javascript:window.history.back();">
                                    << Back</a></b></p>
                    </div>
                <?php } else { ?>
                    <div class="alert alert-success" role="alert">
                        <div class="row">
                            <div class="col-md-12">
                                <h3>Installation Completed Successfully!</h3>
                                <p class="lead">You <b>MUST</b> ensure you remove the entire <b><em>setup/</em></b> directory. Leaving the setup directory in place is a very
                                    serious potential security issue which may lead to deletion or alteration of files, etc.
                                    Please note that until this directory is removed, Boostack will not operate and a warning message will be displayed.
                                </p>
                                <p class="lead" class="text-end"><b><a href="../../">Go to Boostack Homepage >></a></b></p>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
<?php
} else {
?>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-md-9">
                <div class="card-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="pt-2 row">
                        <p>&nbsp;</p>
                    </div>
                    <div class="col-md-12">
                        <div class="card setupInstaller panel-default mb-4">
                            <div>
                                <div class="card-body bg-light">
                                    <form method="post" action="" class="form-horizontal">
                                        <div class="text-center py-3">
                                            <div class="lead">All configurations are preset to ensure the correct installation of Boostack in a Docker environment.
                                                <br>Proceed with submitting the form.
                                            </div>

                                            <div class="col-sm-3 mx-auto mt-3">
                                                <button type="submit" class="btn btn-success w-100">Save</button>
                                            </div>

                                        </div>
                                        <div class="card card-info">
                                            <div class="card-header">
                                                <a class="btn btn-light w-100 text-start" data-bs-toggle="collapse" href="#collapseGeneral" role="button" aria-expanded="false" aria-controls="collapseGeneral">
                                                    <h5 class="card-title card-title my-1">General</h5>
                                                </a>
                                            </div>
                                            <div class="card-body collapse" id="collapseGeneral">

                                                <div class="mb-3 row">
                                                    <label for="current_environment" class="col-sm-3 col-form-label">Environment</label>
                                                    <div class="col-sm-9">
                                                        <select name="current_environment" id="current_environment" class="form-control">
                                                            <option value="LOCAL">LOCAL</option>
                                                            <option value="STAGING">STAGING</option>
                                                            <option value="PRE_PRODUCTION">PRE_PRODUCTION</option>
                                                            <option value="PRODUCTION">PRODUCTION</option>
                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="mb-3 row">
                                                    <label for="dr" class="col-sm-3 col-form-label">Current Document Root</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" readonly disabled id="dr" name="dr" class="form-control-plaintext" id="staticEmail" value="<?php echo $_SERVER['DOCUMENT_ROOT'] ?>" />
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label for="rootpath" class="col-sm-3 col-form-label">Rootpath</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" readonly class="form-control" id="rootpath" name="rootpath" placeholder="/" value="<?php echo $init_rootpath ?>" />
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label for="url" class="col-sm-3 col-form-label">Protocol</label>
                                                    <div class="col-sm-9">
                                                        <select name="protocol" readonly id="protocol" class="form-control">
                                                            <option value="http">http://</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label for="port" class="col-sm-3 col-form-label">Port</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" readonly class="form-control" id="port" name="port" placeholder="port" value="<?php echo substr($init_port, 1) ?>" />
                                                    </div>
                                                </div>

                                                <div class="mb-3 row">
                                                    <label for="dn" class="col-sm-3 col-form-label">Domain Name</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" readonly class="form-control" id="dn" name="dn" placeholder="domain name" value="<?php echo $init_domainname ?>" />
                                                    </div>
                                                </div>

                                                <div class="mb-3 row">
                                                    <label class="col-sm-3 col-form-label">URL</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" readonly class="form-control" id="url" name="url" readonly value="<?= 'http://' . $init_domainname . '' . $init_port . $init_rootpath; ?>" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="card card-info mt-3">
                                            <div class="card-header">
                                            <a class="btn btn-light w-100 text-start" data-bs-toggle="collapse" href="#collapseDatabase" role="button" aria-expanded="false" aria-controls="collapseDatabase">
                                                    <h5 class="card-title card-title my-1">Database</h5>
                                                </a>
                                            </div>
                                            <div class="card-body collapse" id="collapseDatabase">
                                                <div class="noHide">
                                                    <h6>Database</h6>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="hidden" name="db-active" id="db-true" value="true" checked />
                                                    </div>
       
                                                </div>
                                                <div rel="db-active">
                                                    <div class="form-group">
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" type="hidden" name="db-dump-active" id="db-dump-true" value="true" checked readonly />
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">
                                                        <label for="driver-PDO" class="col-sm-2 col-form-label">Driver PDO</label>
                                                        <div class="col-sm-9">
                                                            <select id="driver-PDO" readonly name="driver-PDO" class="form-control">
                                                                <option value="mysql">mysql</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">
                                                        <label for="db-host" class="col-sm-2 col-form-label">Host</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" readonly class="form-control" id="db-host" name="db-host" placeholder="127.0.0.1" value="mariadb<?php #echo $init_ip ?>" />
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">
                                                        <label for="db-port" class="col-sm-2 col-form-label">Port</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" readonly class="form-control" id="db-port" name="db-port" placeholder="3306" value="3306" />
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">
                                                        <label for="db-name" class="col-sm-2 col-form-label">DB Name</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" readonly class="form-control" id="db-name" name="db-name" placeholder="boostack" value="<?=$init_db_database?>" />
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">
                                                        <label for="db-username" class="col-sm-2 col-form-label">Username</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" readonly class="form-control" id="db-username" name="db-username" placeholder="root" value="<?=$init_db_username?>" />
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">
                                                        <label for="db-password" class="col-sm-2 col-form-label">Password</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" readonly class="form-control" id="db-password" name="db-password" placeholder="" value="<?=$init_db_password?>" autocomplete="off" />
                                                        </div>
                                                    </div>
                                                    <div class="mb-3 row">

                                                        <div class="col-sm-9">
                                                            <button id="btnCheckDB" class="btn btn-primary btn-sm d-none">Test Database</button>
                                                            <p><span id="dbStatusIcon"></span><span id="dbStatus"></span></p>
                                                        </div>
                                                    </div>

                                                    <hr />

                                                    <div class="form-group">
                                                        <p class="mb-0 pt-1">Session</p>
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" readonly type="radio" name="db-session-active" id="db-session-true" value="true" checked />
                                                            <label class="form-check-label" for="db-session-true">
                                                                Yes
                                                            </label>
                                                        </div>
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" readonly type="radio" name="db-session-active" id="db-session-false" value="false" />
                                                            <label class="form-check-label" for="db-session-false">
                                                                No
                                                            </label>
                                                        </div>
                                                    </div>



                                                    <div class="form-group d-none">
                                                        <label for="csrf-on" class="col-sm-2 control-label">CSRF</label>
                                                        <div class="col-sm-8">
                                                            <label class="radio-inline">
                                                                <input type="radio" name="db-csrf-active" id="csrf-true" value="true" checked> Yes
                                                            </label>
                                                            <label class="radio-inline">
                                                                <input type="radio" name="db-csrf-active" id="csrf-false" value="false"> No
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <hr />
                                                    <div class="form-group noHideCookie">
                                                        <p class="mb-0 pt-1">Cookie</p>
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" readonly type="radio" name="db-cookie-active" id="db-cookie-true" value="true" checked />
                                                            <label class="form-check-label" for="db-cookie-true">
                                                                Yes
                                                            </label>
                                                        </div>
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" readonly type="radio" name="db-cookie-active" id="db-cookie-false" value="false" />
                                                            <label class="form-check-label" for="db-cookie-false">
                                                                No
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="mb-3 row">
                                                            <label for="db-cookie-expired" class="col-sm-2 col-form-label">Expired(seconds)</label>
                                                            <div class="col-sm-9">
                                                                <input type="text" readonly class="form-control" id="db-cookie-expired" name="db-cookie-expired" placeholder="29 days" value="2505600" />
                                                            </div>
                                                        </div>
                                                        <div class="mb-3 row">
                                                            <label for="db-cookie-name" class="col-sm-2 col-form-label">Name</label>
                                                            <div class="col-sm-9">
                                                                <input type="text" readonly class="form-control" id="db-cookie-name" name="db-cookie-name" placeholder="" value="_<?php echo substr(md5(time()), 0, 9) ?>" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <hr />
                                                    <div class="form-group">
                                                        <p class="mb-0 pt-1">Log</p>
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" readonly type="radio" name="db-log-active" id="db-log-true" value="true" checked />
                                                            <label class="form-check-label" for="db-log-true">
                                                                Yes
                                                            </label>
                                                        </div>
                                                        <div class="form-check form-check-inline">
                                                            <input class="form-check-input" readonly type="radio" name="db-log-active" id="db-log-false" value="false" />
                                                            <label class="form-check-label" for="db-log-false">
                                                                No
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>

                                                <hr />
                                                <div class="form-group">
                                                    <p class="mb-0 pt-1">REST API</p>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="api-active" id="api-active-true" value="true" checked />
                                                        <label class="form-check-label" for="api-active-true">
                                                            Yes
                                                        </label>
                                                    </div>
                                                    <div class="form-check form-check-inline">
                                                        <input class="form-check-input" type="radio" name="api-active" id="api-active-false" value="false" />
                                                        <label class="form-check-label" for="api-active-false">
                                                            No
                                                        </label>
                                                    </div>
                                                </div>

                                                <div class="d-none">
                                                    <div class="form-group">
                                                        <hr />
                                                        <label for="lockStrategy-on-true" class="col-sm-2 control-label">Login Lock Strategy</label>
                                                        <div class="col-sm-8">
                                                            <label class="radio-inline">
                                                                <input type="radio" name="db-lockStrategy_on" id="lockStrategy-on-true" value="true"> Yes
                                                            </label>
                                                            <label class="radio-inline">
                                                                <input type="radio" name="db-lockStrategy_on" id="lockStrategy-on-false" value="false" checked> No
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="login_max_attempts" class="col-sm-2 control-label">Login Max Attempts</label>
                                                        <div class="col-sm-8">
                                                            <span data-toggle="tooltip" data-placement="top" title="Max Login Attempts before user gets blocked before proceding with login">
                                                                <input type="number" class="form-control" id="login_max_attempts" name="db-loginLock-max-attempts" min="0" max="10" value="3" />
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="lockStrategy-true" class="col-sm-2 control-label">Recaptcha or Timer?</label>
                                                        <div class="col-sm-8">
                                                            <span data-toggle="tooltip" data-placement="top" title="User login gets blocked with Google reCAPTCHA">
                                                                <label class="radio-inline">
                                                                    <input type="radio" name="db-loginLock-type" id="recaptcha" value="recaptcha"> Recaptcha
                                                                </label>
                                                            </span>
                                                            <span data-toggle="tooltip" data-placement="top" title="User login gets blocked for X seconds">
                                                                <label class="radio-inline">
                                                                    <input type="radio" name="db-loginLock-type" id="timer" value="timer"> Timer
                                                                </label>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="recaptcha_public" class="col-sm-2 control-label">Public key recaptcha</label>
                                                        <div class="col-sm-8">
                                                            <input type="text" class="form-control" id="recaptcha_public" name="db-loginLock-recaptcha-public" />
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="recaptcha_private" class="col-sm-2 control-label">Private key recaptcha</label>
                                                        <div class="col-sm-8">
                                                            <input type="text" class="form-control" id="recaptcha_private" name="db-loginLock-recaptcha-private" />
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="timer_seconds" class="col-sm-2 control-label">Timer Seconds</label>
                                                        <div class="col-sm-8">
                                                            <span data-toggle="tooltip" data-placement="top" title="Seconds user gets blocked before next attempt to login">
                                                                <input type="number" class="form-control" id="timer_seconds" name="db-loginLock-timer-seconds" min="0" value="180" />
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <hr />
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>