<h2>Controllers</h2>
<p>Controllers can be found in the root folder of the project.</p>
<p>Ax example of default controllers provided by Boostack are <code>index.php</code> or <code>login.php</code></p>
<p>To create a new controller, you can create a brand new file in the root folder of your project and follow the logic above:</p>
<pre><code>&lt;?php
    require_once "core/environment_init.php";


    // INSERT HERE YOUR LOGIC


?&gt;</code></pre>