<h3>Template</h3>
<p>Template can be found in the root folder of the project. And is organized in this way:</p>
<br/>
-Template<br/>
&nbsp;&nbsp;--Partials<br/>
<br/>
<p>The template folder contain the required .phtml like this: </p>
<pre><code>&lt;?php require "partials/pre_content.phtml"; ?&gt;
&lt;?php require "partials/header.phtml"; ?&gt;
&lt;?php require "partials/index.phtml"; ?&gt;
&lt;?php require "partials/footer.phtml"; ?&gt;
&lt;?php require "partials/after_content.phtml"; ?&gt;</code>
</pre>
<p> file and the partials folder contain the content of required .phtml file.</p>
<p>To create a new template, you can create a brand new file in the root folder of your project and follow the logic above:</p>
<pre><code>&lt;?php
    require_once "core/environment_init.php";

    // INSERT HERE YOUR LOGIC



    // If you just need to render your template use this function
        Template::render("yourController.phtml");
    // If you need variable on your template you can use array parameter into template render function
        Template::render("yourController.phtml", array(
            "key" => value,
            "key" => value
            ));
?&gt;</code></pre>