<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<div class="container">
    <div class="row">
        <div class="col-md-12">

            <?php if(!empty($errorMessage)): ?>
                <div class="alert alert-danger" role="alert">
                    <?= $errorMessage ?>
                </div>
            <?php endif; ?>

            <h3>PHP Version</h3>
            <table class="table table-bordered">
                <thead>
                    <th>Your</th>
                    <th>Required >=</th>
                    <th>Status</th>
                </thead>
                <tbody>
                    <tr>
                        <td><?= $phpVersion ?></td>
                        <td><?= $required_php_version[0] ?></td>
                        <td class="<?= $phpVersionResult ? "success" : "danger" ?>"><?= $phpVersionResult ?></td>
                    </tr>
                </tbody>
            </table>



            <h3>Required Apache Modules</h3>
            <table class="table table-bordered">
                <thead>
                    <th>Module</th>
                    <th>Status</th>
                </thead>
                <tbody>
                <?php foreach($apacheModulesRequiredTable as $name => $value): ?>
                    <tr>
                        <td><?= $name ?></td>
                        <td class="<?= $value ? "success" : "danger" ?>"><?= $value ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <h3>Optional Apache Modules</h3>
            <table class="table table-bordered">
                <thead>
                    <th>Module</th>
                    <th>Status</th>
                </thead>
                <tbody>
                <?php foreach($apacheModulesOptionalTable as $name => $value): ?>
                    <tr>
                        <td><?= $name ?></td>
                        <td class="<?= $value ? "success" : "danger" ?>"><?= $value ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <h3>Required PHP Extensions</h3>
            <table class="table table-bordered">
                <thead>
                <th>Extension</th>
                <th>Status</th>
                </thead>
                <tbody>
                <?php foreach($phpExtensionsRequiredTable as $name => $value): ?>
                    <tr>
                        <td><?= $name ?></td>
                        <td class="<?= $value ? "success" : "danger" ?>"><?= $value ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <h3>Required PHP Configurations</h3>
            <table class="table table-bordered">
                <thead>
                <th>Configuration</th>
                <th>Status</th>
                </thead>
                <tbody>
                <?php foreach($phpConfigurationTable as $name => $value): ?>
                    <tr>
                        <td><?= $name ?></td>
                        <td class="<?= $value ? "success" : "danger" ?>"><?= $value ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <h3>Environment setup</h3>
            <form method="post" action="" class="form-horizontal">


                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">General</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="rootpath" class="col-sm-2 control-label">Rootpath</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="rootpath" name="rootpath" placeholder="/" value="/">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="url" class="col-sm-2 control-label">URL</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="url" name="url" placeholder="boostack.local" value="boostack.dev">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Database</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="db-true" class="col-sm-2 control-label">Database</label>
                            <div class="col-sm-8">
                                <label class="radio-inline">
                                    <input type="radio" name="db-active" id="db-true" value="true" checked> Yes
                                </label>
                                <label class="radio-inline">
                                    <input type="radio" name="db-active" id="db-false" value="false"> No
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="db-host" class="col-sm-2 control-label">Host</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="db-host" name="db-host" placeholder="127.0.0.1" value="127.0.0.1">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="db-name" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="db-name" name="db-name" placeholder="boostack" value="boostack">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="db-username" class="col-sm-2 control-label">Username</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="db-username" name="db-username" placeholder="root" value="root">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="db-password" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-8">
                                <input type="password" class="form-control" id="db-password" name="db-password" placeholder="" value="">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Other</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="session-true" class="col-sm-2 control-label">Session</label>
                            <div class="col-sm-8">
                                <label class="radio-inline">
                                    <input type="radio" name="session-active" id="session-true" value="true" checked> Yes
                                </label>
                                <label class="radio-inline">
                                    <input type="radio" name="session-active" id="session-false" value="false"> No
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Save</button>
                    </div>
                </div>
            </form>

        </div>
    </div>




</div>



