<?php
use Boostack\Models\Request;
?>
<div class="row">
    <div class="col-md-9">
        <h2>Template</h2>
        <p>Template can be found in the root folder of the project. And is organized in this way:</p>
        <br />
        -Template<br />
        &nbsp;&nbsp;--Partials<br />
        <br />
        <p>The template folder contain the required .phtml like this: </p>
        <pre><code>&lt;?php require "partials/before_content.phtml"; ?&gt;
&lt;?php require "partials/header.phtml"; ?&gt;
&lt;?php require "partials/index.phtml"; ?&gt;
&lt;?php require "partials/footer.phtml"; ?&gt;
&lt;?php require "partials/after_content.phtml"; ?&gt;</code>
</pre>
        <p> file and the partials folder contain the content of required .phtml file.</p>
        <p>To create a new template, you can create a brand new file in the root folder of your project and follow the logic above:</p>
        <pre><code>&lt;?php
    require_once "core/environment_init.php";

    // INSERT HERE YOUR LOGIC



    // If you just need to render your template use this function
        View::render("yourController.phtml");
    // If you need variable on your template you can use array parameter into template render function
        View::render("yourController.phtml", array(
            "key" => value,
            "key" => value
            ));
?&gt;</code></pre>
        <div class="col-md-3">
            <ul class="list-unstyled sticky-top small lh-lg">
                <li class="item"><a class="link-secondary link-opacity-75-hover link-underline-light fw-light d-none" title="" href="<?= Request::getFriendlyUrl("docs/setup#item") ?>">Item</a></li>
            </ul>
        </div>
    </div>